apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-server-deployment
spec:
  selector:
    matchLabels:
      app: fastapi-server
  template:
    metadata:
      labels:
        app: fastapi-server
    spec:
      containers:
        - image: {{cookiecutter.harbor_registry_project_path}}/fastapi-server:0.1.0
          imagePullPolicy: Always
          name: fastapi-server
          resources:
            requests:
              memory: "4Gi"
              cpu: "4"
            limits:
              memory: "4Gi"
              cpu: "4"
          ports:
            - containerPort: 8080
              name: fastapi-server
          volumeMounts:
            - name: fastapi-server-persistent-storage
              mountPath: /home/aisg/from-ecs
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: ecs-s3-credentials
                  key: awsAccessKeyID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: ecs-s3-credentials
                  key: awsSecretAccessKey
            - name: MLFLOW_S3_ENDPOINT_URL
              valueFrom:
                secretKeyRef:
                  name: ecs-s3-credentials
                  key: ecsS3EndpointURL
      imagePullSecrets:
        - name: harbor-credentials
      volumes:
        - name: fastapi-server-persistent-storage
          persistentVolumeClaim:
            claimName: fstore-rwx-pvc
